const categories = [
    "Beauty & Cosmetic",
    "Oral Care",
    "Antiseptic & Disinfectant",
    "Anti-Hypertensive",
    "Anti-Histamin/Allergy",
    "Cough & Cold",
    "Cream and Ointment",
    "Eye and Ear",
    "ENT DROPS",
    "Anti-Coagulants",
    "Allergy",
    "NSAIDs",
    "Steroids",
    "Anti-Fungal",
    "Personal Care",
    "Men's Care",
    "Health Kits",
    "Medical Equipment",
    "Digital Stethoscope",
    "Herbal",
    "Herbal Tea",
    "Oil",
    "Baby Food",
    "Health and Beauty",
    "Baby Products",
    "Surgical Items & Equipment",
    "Diuretics",
    "Pain Relief",
    "Anti-Thyroid",
    "Vitamin & Supplements",
    "Anti-Inflammatory",
    "Anti-Biotic",
    "Gastrology",
    "Cardiac",
    "Diabetes",
    "Anti-Cold",
    "Asthma",
    "Ayurveda",
    "Women Hygiene",
    "Anti-Cancer",
];

export default categories;
